name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openpyxl
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build EXE
        run: pyinstaller --onefile script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mon-exe
          path: dist/*.exe
